### Que. What is Numpy?
* Numpy stands for Numerical Python
* Numpy - is a python package used for working with array
* Numpy is the fundamental package for scientific computation in python
* Numpy provides various functions which are capable of performing many numeric computation with High speed.
* Numpy provides the in-built functions for linear algebra and random number generation

### Que. By whom & when Numpy was created?
* Travis Oliphant created Numpy in the year 2005.

### Que. Why use Numpy?
* in python we have a list that serves the same purpose of arrays, but they are slow to process
* numpy is 50x faster than traditional python lists.
* an array object in NumPy is called ndarray
* Arrays are frequently used in DataScience, where speed and resources are very important

- array is a collection of homogenous(same) data

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

#### point 1: Changing size

list - 32 bytes to store 5 element 6 64 bytes
numpy - 32 bytes to store 5 elememts 6 38 bytes

#### point 2: Memory size
list = [1,"afsan",10.2]
numpy = [1,1,1]

#### point 3: Statistical functions 
list - find the mean of the element inside a list - Write your own code

numpy - methods - one liner - less code

#### points 4: Package (sckiti learn, ml packages, dl packages, Genai packages)

list -> package --> numpy convert


In [1]:
# install numpy
!pip install numpy  # '!' tell its not python code, its a terminal command

In [4]:
# import 

import numpy as np 

In [6]:
# list
list_data = [10,24,54,32,27,36]

print(np.array(list_data))
print(type(np.array(list_data))) # class ndarray.

[10 24 54 32 27 36]
<class 'numpy.ndarray'>


#### Different type of arrays
* 1D array - vector
* 2D array - matrix [rows and columns]
* 3d array - 3d matrix [Tensor] [row, column and dept]

In [15]:
# creating 2D and 3D arrays 
list_2= [[1,2,3],[4,5,6]]
print(np.array(list_2))

list_3 = [[[1,2,3],[4,5,6,]],[[1,2,3],[4,5,6]]] # This is 3D 2 of 2*3 (i.e array(2,3,2))
print(np.array(list_3))

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
# 1. dtype -> used to change data type of an array 
np.array(list_2, dtype= float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
# 2. arange -> works same as range, only difference is it return array

print(np.arange(1,10))
print(np.arange(1,10,2))

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [ ]:
#3. linspace (linear space) (min, max, num (break it into  n equal parts))

print(np.linspace(1,10,2))
print(np.linspace(1,50,10))

# Note min and max both are inclusive in this method. 
# 6.4444-1.0 === 11.888-6.444 == 17.3333-11.888, distance between any two consecutive numbers will be constant/same. 

[ 1. 10.]
[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [ ]:
# note: arange and linspace return 1D data only. 

In [ ]:
# 4 zeros: to create a array of all elements zero, takes a shape in form of iterable.

print(np.zeros(3)) # vector of zeros
print(np.zeros((2,3),dtype= int)) # 2D zeros matrix
print(np.zeros([2,3],dtype= int)) # 2D zeros matrix
print(np.zeros((2,3,2),dtype= int)) # 3d zeros matrix

[0. 0. 0.]
[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


In [ ]:
# 5 ones: to create a array of all elements ones, takes a shape in form of iterable.
print(np.ones(3)) # vector of zeros
print(np.ones((2,3),dtype= int)) # 2D zeros matrix
print(np.ones((2,3,2),dtype= int)) # 3d zeros matrix

[1. 1. 1.]
[[1 1 1]
 [1 1 1]]
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [ ]:
# 6. Identity matrix: creates an idenity matrix, 1's on diagnol, shapes has to be sqaure matrix (i.e row== column)

print(np.eye(5)) # Gives 5*5 matrix 
print(np.identity(5)) # same as eye 

# only difference is, in eye you can allow none square dimensions, identity doesn't allow 
print(np.eye(2,3))
# print(np.identity(2,3))# throws error. 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]]


TypeError: Cannot interpret '3' as a data type

In [ ]:
#7.  random

print(np.random.rand(2,3)) # [0,1) uniform distribution
print(np.random.randint(1,10,(2,3))) # low, high, shape, return int 
print(np.random.random((2,3))) # [0,1), returns float 

[[0.076076   0.02480317 0.05736769]
 [0.66069015 0.65784666 0.70604493]]
[[8 3 9]
 [6 3 9]]
[[0.30010507 0.23470751 0.95527375]
 [0.93819595 0.75277278 0.0019858 ]]


In [ ]:
# 8. reshape(): gives new shape to an array without changing the data 

a= np.arange(10)
print(a) # vector of elements from 1 to 10 
print(a.reshape(2,5)) # it is transformed to 2*5 matrix. Note: 2*5= 10 elements, if number of elements didnt match it would throw error. 
# print(a.reshape(1,6)) # this will throw error as 1*6 !=10. 

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [82]:
# infer: you specify only few dim and infer other while reshapping. (Note: you can only infer once)

b= np.arange(50)
print(b.reshape(-1,10)) # specifying number columns to be 10, infering number of rows. 
print(b.reshape(-1,2,5)) # specifying number of rows and columns, infering depth. 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]]


In [ ]:
# Array attributes: 
a1 = np.arange(10,dtype=np.int32) # 1d here we are converting it to int32 
a2 = np.arange(12,dtype=float).reshape(3,4) # 2d
a3 = np.arange(8,).reshape(2,2,2) # 3d, here we aren't specifying it thus, it take default which is data type of 8.
a4 = np.arange(8.0,).reshape(2,2,2)

In [ ]:
# 9. ndim: gives dimension of an array

print(a1.ndim) # 1 i.e vector 
print(a2.ndim) # 2 i.e matrix 
print(a3.ndim) # 3 i.e tensor, 3d matrix 

1
2
3


In [61]:
# 10. shape: gives tuple of rows, column and depth of an array 
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [62]:
# 11. size: gives total number of elements

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [ ]:
# 12. itemsize: gives the size of an element in an array

print(a1.itemsize) # size each elements are taking 4 bytes, i.e int->4 bytes, float-> 8 bytes 
print(a2.itemsize) # as it type casted to float, each elements take 8 bytes 
print(a3.itemsize) # here we didnt type casted a datatype, then it take default of int64 or 8 bytes. 

4
8
8


In [ ]:
# 13. dtype: gives datatype of an element in array 
print(a1.dtype) # int32
print(a2.dtype) # float64
print(a3.dtype) # int64
print(a4.dtype) # float64 because you use 8.0 instead of 8 like a3. 

int32
float64
int64
float64


In [ ]:
# 14. astype:  Changing data type of an array
a1.astype(np.int32) # you will need to save it in need variable or use copy by default copy =True
a2.astype(np.float32)
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [83]:
# 15. Transpose: flipping matrix such that rows become columns and columns become rows. 

a2 = np.arange(18).reshape(6,3)
print(a2)
print(a2.shape)
print(a2.T)
print(a2.T.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
(6, 3)
[[ 0  3  6  9 12 15]
 [ 1  4  7 10 13 16]
 [ 2  5  8 11 14 17]]
(3, 6)


### Basic Array Operations 

In [84]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [86]:
# scalar operations: works with all arithematic operations 

print(a1*2)
print(a1/2)
print(a2%2)
print(a1//2)
print(a1**2)


[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [87]:
# Relational Operator: works with all relational arrays 

print(a1>5)
print(a1==5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False  True False False]
 [False False False False]]


In [88]:
# Vector Operation: Operation between two vectors (all arithmetic operations)

print(a1+a2)
print(a1-a2)
print(a1/a2)
print(a1**a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]


In [92]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)

In [96]:
print(a1)
print(a2)

print(a1*a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


In [93]:
# Matrix Multipication : (Dot product)

print(np.dot(a,b))


[[ 58  64]
 [139 154]]


### Universal Functions

In [116]:
a1 = np.arange(24)
a2 = np.arange(24).reshape(4,6)

In [ ]:
# sum: sum of all the elements in an array

print(a1.sum())
print(a2.sum())

276
276


In [ ]:
# sum: sum of all the rows or columns, use axis parameter axis=0 => columns, axis=1 => rows

print(a2.sum(axis=1))
print(a2.sum(axis=0))

[ 15  51  87 123]
[36 40 44 48 52 56]


In [ ]:
# prod: prodcut of all the elements, use axis parameter axis=0 => columns, axis=1 => rows

print(a1.prod())
print(a2.prod(axis=0))
print(a2.prod(axis=1))

0
[    0  1729  4480  8505 14080 21505]
[       0   332640  8910720 72681840]


In [ ]:
# max 
print(a1.max())
print(a2.max(axis=0))
print(a2.max(axis=1))

23
[18 19 20 21 22 23]
[ 5 11 17 23]


In [114]:
# min
print(a1.min())
print(a2.min(axis=0))
print(a2.min(axis=1))

0
[0 1 2 3 4 5]
[ 0  6 12 18]


In [120]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [126]:
# add
print(np.add(a1,a2))

# subtract
print(np.subtract(a1,a2))

# square 
print(np.square(a1))

# log 
print(np.log(a1))

# sqrt 
print(np.sqrt(a1))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]
[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]


/var/folders/xw/_lnfz_x56cn_zn8_slshkwp80000gn/T/ipykernel_90329/1178886505.py:11: RuntimeWarning: divide by zero encountered in log
  print(np.log(a1))


In [129]:
# Trignometry functions: 

# sin 
print(np.sin(a1))

# cos
print(np.cos(a1))

# tan
print(np.tan(a1))


# Note: when to you np, versus when note, check dir 

dir(a1) # gives list of all function avaialble 

# you need to use np, if available in the list, but its better to use np rather. 

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]
[[ 1.          0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029  0.75390225]
 [-0.14550003 -0.91113026 -0.83907153  0.0044257 ]]
[[ 0.00000000e+00  1.55740772e+00 -2.18503986e+00 -1.42546543e-01]
 [ 1.15782128e+00 -3.38051501e+00 -2.91006191e-01  8.71447983e-01]
 [-6.79971146e+00 -4.52315659e-01  6.48360827e-01 -2.25950846e+02]]


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [ ]:
# Statistical 

# mean
print(np.mean(a1))

# median
print(np.median(a1))

# std 
print(np.std(a1))

# variance
print(np.var(a1))

5.5
5.5
3.452052529534663
11.916666666666666


### Indexing and Slicing

In [5]:
a1 = np.arange(10) # 1 Dim 
a2 = np.arange(10,50).reshape(4,10) # 2 Dim
a3 = np.arange(10,50).reshape(4,2,5) # 3 Dim 

print(a1, a2, a3)

[0 1 2 3 4 5 6 7 8 9] [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]] [[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]]


In [33]:
# Indexing: to get 1 value 

# For 1 Dim (Same as list)
print(a1[-2])
print(a1[3])

# For 2 Dim [Row, Column]
print(a2[1,7])
print(a2[1,-3]) # can use negative index as well.
print(a2[2,4])

# For 3 Dim (Depth, Row, Column)
print(a3[2,0,-1])
print(a3[1,1,3])

8
3
27
27
34
34
28


In [34]:
print(a3)

[[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]]


In [35]:
# Slicing: to get multiple values

# For 1 Dim (Same as list)
print(a1[-4:-7:-1]) # -1 step to print backwards
print(a1[6:3:-1])

# For 2 Dim [slicing for rows, slicing for colums] (Way of gettig subarray)
print(a2[1:3,-4:-2])
print(a2[2:0:-1,-2:-4:-1])
print(a2[1:4, 5:8:2])
print(a2[::2,5::3 ]) # start, stop and step 
print(a2[::-2, 4::2 ])

# For 3-Dim [slicing for depth, slicing for row, slicing for column]
print(a3[2,::-1, -2::])

[6 5 4]
[6 5 4]
[[26 27]
 [36 37]]
[[38 37]
 [28 27]]
[[25 27]
 [35 37]
 [45 47]]
[[15 18]
 [35 38]]
[[44 46 48]
 [24 26 28]]
[[38 39]
 [33 34]]
